apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hdl-library-axi_intr_monitor-2027_r1
  title: AXI_INTR_MONITOR HDL IP core 2027_r1
  description: AXI_INTR_MONITOR HDL IP core 2027_r1
  version: 2027_r1
  classification: software
  license:
  - ADI BSD License
  annotations:
    backstage.io/source-location: url:https://github.com/gastmaier/hdl-temp/tree/2027_r1/library/axi_intr_monitor
  tags:
  - hdl
  - ip-core
  - library
  links:
  - url: https://github.com/gastmaier/hdl-temp/tree/2027_r1/library/axi_intr_monitor
    title: Source code
    icon: web
spec:
  owner: group:default/hdl-sw-team
  type: source
  lifecycle: sustain
  subcomponentOf: hdl-library-axi_intr_monitor
