apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hdl-library-spi_engine-axi_spi_engine-2027_r1
  title: AXI_SPI_ENGINE HDL IP core 2027_r1
  description: >
    The AXI SPI Engine IP core allows asynchronous interrupt-driven memory-mapped
    access to a SPI Engine Control Interface. This is typically used in combination
    with a software program to dynamically generate SPI transactions.

    The peripheral has also support for providing memory-mapped access to one or more
    spi_engine offload cores and change its content dynamically at runtime.
  version: 2027_r1
  classification: software
  license:
  - ADI BSD License
  annotations:
    backstage.io/source-location: url:https://github.com/gastmaier/hdl-temp/tree/2027_r1/library/spi_engine/axi_spi_engine
  tags:
  - hdl
  - ip-core
  - library
  links:
  - url: https://github.com/gastmaier/hdl-temp/tree/2027_r1/library/spi_engine/axi_spi_engine
    title: Source code
    icon: web
  - url: https://gastmaier.github.io/hdl-temp/2027_r1/library/spi_engine/axi_spi_engine.html
    title: Documentation
    icon: web
spec:
  owner: group:default/hdl-sw-team
  type: source
  lifecycle: sustain
  subcomponentOf: hdl-library-spi_engine-axi_spi_engine
  dependsOn:
  - Component:hdl-library-util_axis_fifo-2027_r1
  - Component:hdl-library-util_cdc-2027_r1
