apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hdl-library-intel-avl_adxphy-2027_r1
  title: AVL_ADXPHY HDL IP core 2027_r1
  description: AVL_ADXPHY HDL IP core 2027_r1
  version: 2027_r1
  classification: software
  license:
  - ADI BSD License
  annotations:
    backstage.io/source-location: url:https://github.com/gastmaier/hdl-temp/tree/2027_r1/library/intel/avl_adxphy
  tags:
  - hdl
  - ip-core
  - library
  links:
  - url: https://github.com/gastmaier/hdl-temp/tree/2027_r1/library/intel/avl_adxphy
    title: Source code
    icon: web
spec:
  owner: group:default/hdl-sw-team
  type: source
  lifecycle: sustain
  subcomponentOf: hdl-library-intel-avl_adxphy
