apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hdl-project-dac_fmc_ebz-vcu118-2027_r1
  title: DAC_FMC_EBZ_VCU118 HDL project 2027_r1
  description: DAC_FMC_EBZ_VCU118 HDL project 2027_r1
  version: 2027_r1
  classification: software
  license:
  - ADI BSD License
  annotations:
    backstage.io/source-location: url:https://github.com/gastmaier/hdl-temp/tree/2027_r1/projects/dac_fmc_ebz/vcu118
  tags:
  - hdl
  - project
  - reference-design
  - vcu118
  links:
  - url: https://github.com/gastmaier/hdl-temp/tree/2027_r1/projects/dac_fmc_ebz/vcu118
    title: Source code
    icon: web
spec:
  owner: group:default/hdl-sw-team
  type: source
  lifecycle: sustain
  subcomponentOf: hdl-project-dac_fmc_ebz-vcu118
  dependsOn:
  - Component:hdl-library-axi_dmac-2027_r1
  - Component:hdl-library-axi_sysid-2027_r1
  - Component:hdl-library-jesd204-ad_ip_jesd204_tpl_adc-2027_r1
  - Component:hdl-library-jesd204-ad_ip_jesd204_tpl_dac-2027_r1
  - Component:hdl-library-jesd204-axi_jesd204_rx-2027_r1
  - Component:hdl-library-jesd204-axi_jesd204_tx-2027_r1
  - Component:hdl-library-jesd204-jesd204_rx_static_config-2027_r1
  - Component:hdl-library-jesd204-jesd204_tx-2027_r1
  - Component:hdl-library-sysid_rom-2027_r1
  - Component:hdl-library-util_dacfifo-2027_r1
  - Component:hdl-library-util_pack-util_upack2-2027_r1
  - Component:hdl-library-xilinx-axi_adxcvr-2027_r1
  - Component:hdl-library-xilinx-util_adxcvr-2027_r1
