apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hdl-library-axi_ad9361
  title: AXI AD9361 HDL IP core
  description: >
    The AXI AD9361 IP core can be used to interface the AD9361 device. This documentation
    only covers the IP core and requires that one must be familiar with the device
    for a complete and better understanding.

    More about the generic framework interfacing ADCs can be read in axi_adc, and
    interfacing DACs in axi_dac.
  version: main
  classification: software
  license:
  - ADI BSD License
  annotations:
    backstage.io/source-location: url:https://github.com/gastmaier/hdl-temp/tree/main/library/axi_ad9361
  tags:
  - ad9361
  - hdl
  - ip-core
  - library
  links:
  - url: https://gastmaier.github.io/hdl-temp/library/axi_ad9361/index.html
    title: Documentation
    icon: web
spec:
  owner: group:default/hdl-sw-team
  type: source
  lifecycle: sustain
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hdl-library-axi_ad9361-2027_r1
  title: AXI AD9361 HDL IP core 2027_r1
  description: >
    The AXI AD9361 IP core can be used to interface the AD9361 device. This documentation
    only covers the IP core and requires that one must be familiar with the device
    for a complete and better understanding.

    More about the generic framework interfacing ADCs can be read in axi_adc, and
    interfacing DACs in axi_dac.
  version: 2027_r1
  classification: software
  license:
  - ADI BSD License
  annotations:
    backstage.io/source-location: url:https://github.com/gastmaier/hdl-temp/tree/2027_r1/library/axi_ad9361
  tags:
  - ad9361
  - hdl
  - ip-core
  - library
  links:
  - url: https://github.com/gastmaier/hdl-temp/tree/2027_r1/library/axi_ad9361
    title: Source code
    icon: web
  - url: https://gastmaier.github.io/hdl-temp/2027_r1/library/axi_ad9361/index.html
    title: Documentation
    icon: web
spec:
  owner: group:default/hdl-sw-team
  type: source
  lifecycle: sustain
  subcomponentOf: hdl-library-axi_ad9361
