apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hdl-library-intel-common-intel_serdes
  title: INTEL_SERDES HDL IP core
  description: INTEL_SERDES HDL IP core
  version: main
  classification: software
  license:
  - ADI BSD License
  annotations:
    backstage.io/source-location: url:https://github.com/gastmaier/hdl-temp/tree/main/library/intel/common/intel_serdes
  tags:
  - hdl
  - ip-core
  - library
  links: []
spec:
  owner: group:default/hdl-sw-team
  type: source
  lifecycle: sustain
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hdl-library-intel-common-intel_serdes-2027_r1
  title: INTEL_SERDES HDL IP core 2027_r1
  description: INTEL_SERDES HDL IP core 2027_r1
  version: 2027_r1
  classification: software
  license:
  - ADI BSD License
  annotations:
    backstage.io/source-location: url:https://github.com/gastmaier/hdl-temp/tree/2027_r1/library/intel/common/intel_serdes
  tags:
  - hdl
  - ip-core
  - library
  links:
  - url: https://github.com/gastmaier/hdl-temp/tree/2027_r1/library/intel/common/intel_serdes
    title: Source code
    icon: web
spec:
  owner: group:default/hdl-sw-team
  type: source
  lifecycle: sustain
  subcomponentOf: hdl-library-intel-common-intel_serdes
