apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hdl-project-adaq8092_fmc-zed
  title: ADAQ8092-FMC HDL project
  description: >
    The EVAL-ADAQ8092 evaluates the ADAQ8092, a 14-bit, 105MSPS , high-speed dual-channel
    data acquisition uModule solution. This device uses the System-in-Package (SiP)
    that integrates three common signal processing and conditioning blocks.

    This EVAL-ADAQ8092 board does not need an external power supply to operate and
    requires a very small jitter in the clock source. We recommend to use the DC1075B
    to improve the clock signal source. For full details on the ADAQ8092, see the
    ADAQ8092 data sheet, which must be consulted in conjunction with this user guide
    when using the EVAL-ADAQ8092.

    It targets the AMD Xilinx ZED.
  version: main
  classification: software
  license:
  - ADI BSD License
  annotations:
    backstage.io/source-location: url:https://github.com/gastmaier/hdl-temp/tree/main/projects/adaq8092_fmc/zed
  tags:
  - adaq8092
  - dc1075b
  - eval-adaq8092
  - hdl
  - project
  - reference-design
  - zed
  links:
  - url: https://gastmaier.github.io/hdl-temp/projects/adaq8092_fmc/index.html
    title: Documentation
    icon: web
spec:
  owner: group:default/hdl-sw-team
  type: source
  lifecycle: sustain
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hdl-project-adaq8092_fmc-zed-2027_r1
  title: ADAQ8092-FMC HDL project 2027_r1
  description: >
    The EVAL-ADAQ8092 evaluates the ADAQ8092, a 14-bit, 105MSPS , high-speed dual-channel
    data acquisition uModule solution. This device uses the System-in-Package (SiP)
    that integrates three common signal processing and conditioning blocks.

    This EVAL-ADAQ8092 board does not need an external power supply to operate and
    requires a very small jitter in the clock source. We recommend to use the DC1075B
    to improve the clock signal source. For full details on the ADAQ8092, see the
    ADAQ8092 data sheet, which must be consulted in conjunction with this user guide
    when using the EVAL-ADAQ8092.

    It targets the AMD Xilinx ZED.
  version: 2027_r1
  classification: software
  license:
  - ADI BSD License
  annotations:
    backstage.io/source-location: url:https://github.com/gastmaier/hdl-temp/tree/2027_r1/projects/adaq8092_fmc/zed
  tags:
  - adaq8092
  - dc1075b
  - eval-adaq8092
  - hdl
  - project
  - reference-design
  - zed
  links:
  - url: https://github.com/gastmaier/hdl-temp/tree/2027_r1/projects/adaq8092_fmc/zed
    title: Source code
    icon: web
  - url: https://gastmaier.github.io/hdl-temp/2027_r1/projects/adaq8092_fmc/index.html
    title: Documentation
    icon: web
spec:
  owner: group:default/hdl-sw-team
  type: source
  lifecycle: sustain
  subcomponentOf: hdl-project-adaq8092_fmc-zed
  dependsOn:
  - Component:hdl-library-axi_adaq8092-2027_r1
  - Component:hdl-library-axi_clkgen-2027_r1
  - Component:hdl-library-axi_dmac-2027_r1
  - Component:hdl-library-axi_hdmi_tx-2027_r1
  - Component:hdl-library-axi_i2s_adi-2027_r1
  - Component:hdl-library-axi_spdif_tx-2027_r1
  - Component:hdl-library-axi_sysid-2027_r1
  - Component:hdl-library-sysid_rom-2027_r1
  - Component:hdl-library-util_i2c_mixer-2027_r1
  - Component:hdl-library-util_pack-util_cpack2-2027_r1
