apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hdl-project-ad3552r_evb-zed
  title: EVAL-AD3552R HDL project
  description: >
    The EVAL-AD3552R is an evaluation board for the AD3552R, a dual-channel, 16-bit
    fast precision digital-to-analog converter (DAC). Each channel of the AD3552R
    is equipped with a different transimpedance amplifier: Channel 0 has a fast amplifier
    that achieves the optimal dynamic performance and Channel 1 has a precision amplifier
    that guarantees the optimal DC precision over temperature.

    The board allows testing all the output ranges of the DAC, waveform generation,
    power supply and reference options.

    It targets the AMD Xilinx ZED.
  version: main
  classification: software
  license:
  - ADI BSD License
  annotations:
    backstage.io/source-location: url:https://github.com/gastmaier/hdl-temp/tree/main/projects/ad3552r_evb/zed
  tags:
  - ad3552r
  - eval-ad3552r
  - hdl
  - project
  - reference-design
  - zed
  links:
  - url: https://gastmaier.github.io/hdl-temp/projects/ad3552r_evb/index.html
    title: Documentation
    icon: web
spec:
  owner: group:default/hdl-sw-team
  type: source
  lifecycle: sustain
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hdl-project-ad3552r_evb-zed-2027_r1
  title: EVAL-AD3552R HDL project 2027_r1
  description: >
    The EVAL-AD3552R is an evaluation board for the AD3552R, a dual-channel, 16-bit
    fast precision digital-to-analog converter (DAC). Each channel of the AD3552R
    is equipped with a different transimpedance amplifier: Channel 0 has a fast amplifier
    that achieves the optimal dynamic performance and Channel 1 has a precision amplifier
    that guarantees the optimal DC precision over temperature.

    The board allows testing all the output ranges of the DAC, waveform generation,
    power supply and reference options.

    It targets the AMD Xilinx ZED.
  version: 2027_r1
  classification: software
  license:
  - ADI BSD License
  annotations:
    backstage.io/source-location: url:https://github.com/gastmaier/hdl-temp/tree/2027_r1/projects/ad3552r_evb/zed
  tags:
  - ad3552r
  - eval-ad3552r
  - hdl
  - project
  - reference-design
  - zed
  links:
  - url: https://github.com/gastmaier/hdl-temp/tree/2027_r1/projects/ad3552r_evb/zed
    title: Source code
    icon: web
  - url: https://gastmaier.github.io/hdl-temp/2027_r1/projects/ad3552r_evb/index.html
    title: Documentation
    icon: web
spec:
  owner: group:default/hdl-sw-team
  type: source
  lifecycle: sustain
  subcomponentOf: hdl-project-ad3552r_evb-zed
  dependsOn:
  - Component:hdl-library-axi_ad3552r-2027_r1
  - Component:hdl-library-axi_clkgen-2027_r1
  - Component:hdl-library-axi_dmac-2027_r1
  - Component:hdl-library-axi_hdmi_tx-2027_r1
  - Component:hdl-library-axi_i2s_adi-2027_r1
  - Component:hdl-library-axi_spdif_tx-2027_r1
  - Component:hdl-library-axi_sysid-2027_r1
  - Component:hdl-library-sysid_rom-2027_r1
  - Component:hdl-library-util_i2c_mixer-2027_r1
